'''
Create a program that will play the "cows and bulls" game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they have a "cow".
For every digit the user guessed correctly in the wrong place is a "bull."
Every time the user makes a guess, tell them how many "cows" and "bulls" they have.
Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
  #>>> 1234
  2 cows, 0 bulls
 # >>> 1256
  1 cow, 1 bull
  ...

Until the user guesses the number.

1. generate random 4 digit number
2. user input
3. compare user input to randomly generated number
4. check how many digits the user got correct
'''
import random


def cow_bull():

    play_again = True
    num = str(random.choice(range(1000, 9999)))


    while play_again:

        cow = 0
        bull = 0

        print "I have a four digit number in mind. Can you guess what it is?"
        usr_input = str(raw_input("Enter four digit number_ "))


        i = 0
        for digit in num:
            if digit == usr_input[i]:
                cow += 1
            elif digit in usr_input:
                if digit != usr_input[i]:
                    bull += 1
            i += 1
        if cow < 4:
            print "You have ", cow," cows and ", bull, " bulls."
        elif cow == 4:
            print "You have ", cow," cows and ", bull, " bulls."
            print "You guessed everything correctly, goodbye!"
            play_again = False


if __name__ == '__main__':
    cow_bull()
